/** Official MCPS school names (2025–2026 list). */

export type McpsSchoolGroup = {
  label: string;
  schools: readonly string[];
};

export const MCPS_SCHOOL_GROUPS: Record<string, McpsSchoolGroup> = {
  elementary: {
    label: "Elementary schools",
    schools: [
      "Arcola Elementary School",
      "Ashburton Elementary School",
      "Bannockburn Elementary School",
      "Bayard Rustin Elementary School",
      "Beall Elementary School",
      "Bel Pre Elementary School",
      "Bells Mill Elementary School",
      "Belmont Elementary School",
      "Bethesda Elementary School",
      "Beverly Farms Elementary School",
      "Bradley Hills Elementary School",
      "Brooke Grove Elementary School",
      "Brookhaven Elementary School",
      "Brown Station Elementary School",
      "Burning Tree Elementary School",
      "Burnt Mills Elementary School",
      "Burtonsville Elementary School",
      "Cabin Branch Elementary School",
      "Candlewood Elementary School",
      "Cannon Road Elementary School",
      "Capt. James E. Daly Elementary School",
      "Carderock Springs Elementary School",
      "Cashell Elementary School",
      "Cedar Grove Elementary School",
      "Chevy Chase Elementary School",
      "Clarksburg Elementary School",
      "Clearspring Elementary School",
      "Clopper Mill Elementary School",
      "Cloverly Elementary School",
      "Cold Spring Elementary School",
      "College Gardens Elementary School",
      "Cresthaven Elementary School",
      "Damascus Elementary School",
      "Darnestown Elementary School",
      "Diamond Elementary School",
      "Dr. Charles R. Drew Elementary School",
      "Dr. Sally K. Ride Elementary School",
      "DuFief Elementary School",
      "East Silver Spring Elementary School",
      "Fairland Elementary School",
      "Fallsmead Elementary School",
      "Farmland Elementary School",
      "Fields Road Elementary School",
      "Flora M. Singer Elementary School",
      "Flower Hill Elementary School",
      "Flower Valley Elementary School",
      "Forest Knolls Elementary School",
      "Fox Chapel Elementary School",
      "Gaithersburg Elementary School",
      "Galway Elementary School",
      "Garrett Park Elementary School",
      "Georgian Forest Elementary School",
      "Germantown Elementary School",
      "Glen Haven Elementary School",
      "Glenallan Elementary School",
      "Goshen Elementary School",
      "Great Seneca Creek Elementary School",
      "Greencastle Elementary School",
      "Greenwood Elementary School",
      "Harmony Hills Elementary School",
      "Harriet R. Tubman Elementary School",
      "Highland Elementary School",
      "Highland View Elementary School",
      "Jackson Road Elementary School",
      "JoAnn Leleck Elementary School at at Broad Acres",
      "Jones Lane Elementary School",
      "Judith A. Resnik Elementary School",
      "Kemp Mill Elementary School",
      "Kensington Parkwood Elementary School",
      "Lake Seneca Elementary School",
      "Lakewood Elementary School",
      "Laytonsville Elementary School",
      "Little Bennett Elementary School",
      "Lois P. Rockwell Elementary School",
      "Lucy V. Barnsley Elementary School",
      "Luxmanor Elementary School",
      "Maryvale Elementary School",
      "Meadow Hall Elementary School",
      "Mill Creek Towne Elementary School",
      "Monocacy Elementary School",
      "Montgomery Knolls Elementary School",
      "New Hampshire Estates Elementary School",
      "North Chevy Chase Elementary School",
      "Oak View Elementary School",
      "Oakland Terrace Elementary School",
      "Olney Elementary School",
      "Pine Crest Elementary School",
      "Piney Branch Elementary School",
      "Poolesville Elementary School",
      "Potomac Elementary School",
      "Rachel Carson Elementary School",
      "Ritchie Park Elementary School",
      "Rock Creek Forest Elementary School",
      "Rock Creek Valley Elementary School",
      "Rock View Elementary School",
      "Rolling Terrace Elementary School",
      "Ronald McNair Elementary School",
      "Roscoe R. Nix Elementary School",
      "Rosemary Hills Elementary School",
      "Rosemont Elementary School",
      "S. Christa McAuliffe Elementary School",
      "Sargent Shriver Elementary School",
      "Sequoyah Elementary School",
      "Seven Locks Elementary School",
      "Sherwood Elementary School",
      "Sligo Creek Elementary School",
      "Snowden Farm Elementary School",
      "Somerset Elementary School",
      "South Lake Elementary School",
      "Spark M. Matsunaga Elementary School",
      "Stedwick Elementary School",
      "Stone Mill Elementary School",
      "Stonegate Elementary School",
      "Strathmore Elementary School",
      "Strawberry Knoll Elementary School",
      "Summit Hall Elementary School",
      "Takoma Park Elementary School",
      "Thurgood Marshall Elementary School",
      "Travilah Elementary School",
      "Viers Mill Elementary School",
      "Washington Grove Elementary School",
      "Waters Landing Elementary School",
      "Watkins Mill Elementary School",
      "Wayside Elementary School",
      "Weller Road Elementary School",
      "Westbrook Elementary School",
      "Westover Elementary School",
      "Wheaton Woods Elementary School",
      "Whetstone Elementary School",
      "William Tyler Page Elementary School",
      "Wilson Wims Elementary School",
      "Wood Acres Elementary School",
      "Woodfield Elementary School",
      "Woodlin Elementary School",
      "Wyngate Elementary School",
    ],
  },
  middle: {
    label: "Middle schools",
    schools: [
      "A. Mario Loiederman Middle School",
      "Argyle Middle School",
      "Benjamin Banneker Middle School",
      "Briggs Chaney Middle School",
      "Cabin John Middle School",
      "Dr. Martin Luther King, Jr . Middle School",
      "Earle B. Wood Middle School",
      "Eastern Middle School",
      "Forest Oak Middle School",
      "Francis Scott Key Middle School",
      "Gaithersburg Middle School",
      "Hallie Wells Middle School",
      "Herbert Hoover Middle School",
      "John Poole Middle School",
      "John T. Baker Middle School",
      "Julius West Middle School",
      "Kingsview Middle School",
      "Lakelands Park Middle School",
      "Montgomery Village Middle School",
      "Neelsville Middle School",
      "Newport Mill Middle School",
      "North Bethesda Middle School",
      "Odessa Shannon Middle School",
      "Parkland Middle School",
      "Redland Middle School",
      "Ridgeview Middle School",
      "Robert Frost Middle School",
      "Roberto W. Clemente Middle School",
      "Rocky Hill Middle School",
      "Rosa M. Parks Middle School",
      "Shady Grove Middle School",
      "Silver Creek Middle School",
      "Silver Spring International Middle School",
      "Sligo Middle School",
      "Takoma Park Middle School",
      "Thomas W. Pyle Middle School",
      "Tilden Middle School",
      "Westland Middle School",
      "White Oak Middle School",
      "William H. Farquhar Middle School",
    ],
  },
  high: {
    label: "High schools",
    schools: [
      "Albert Einstein High School",
      "Bethesda-Chevy Chase High School",
      "Clarksburg High School",
      "Col. Zadok Magruder High School",
      "Damascus High School",
      "Gaithersburg High School",
      "James Hubert Blake High School",
      "John F. Kennedy High School",
      "Montgomery Blair High School",
      "Northwest High School",
      "Northwood High School",
      "Paint Branch High School",
      "Poolesville High School",
      "Quince Orchard High School",
      "Richard Montgomery High School",
      "Rockville High School",
      "Seneca Valley High School",
      "Sherwood High School",
      "Springbrook High School",
      "Thomas S. Wootton High School",
      "Walt Whitman High School",
      "Walter Johnson High School",
      "Watkins Mill High School",
      "Wheaton High School",
      "Winston Churchill High School",
    ],
  },
  technical: {
    label: "Technical / career",
    schools: [
    ],
  },
  special: {
    label: "Special schools",
    schools: [
      "Carl Sandburg Learning Center",
      "Longview School",
      "Rock Terrace School",
      "Stephen Knolls School",
    ],
  },
  alternative: {
    label: "Alternative programs",
    schools: [
      "... Blair G. Ewing Center @ Avery Road (Rockville)",
      "... Blair G. Ewing Center @ North Lake Center (Rockville)",
    ],
  },
  early: {
    label: "Early childhood",
    schools: [
      "MacDonald Knolls Early Childhood Center",
      "Upcounty Early Childhood Center (UCECC) at Emory Grove",
    ],
  },
  charter: {
    label: "Charter schools",
    schools: [
    ],
  },
} as const;

export const MCPS_SCHOOL_OPTIONS: readonly string[] = [
  "... Blair G. Ewing Center @ Avery Road (Rockville)",
  "... Blair G. Ewing Center @ North Lake Center (Rockville)",
  "A. Mario Loiederman Middle School",
  "Albert Einstein High School",
  "Arcola Elementary School",
  "Argyle Middle School",
  "Ashburton Elementary School",
  "Bannockburn Elementary School",
  "Bayard Rustin Elementary School",
  "Beall Elementary School",
  "Bel Pre Elementary School",
  "Bells Mill Elementary School",
  "Belmont Elementary School",
  "Benjamin Banneker Middle School",
  "Bethesda Elementary School",
  "Bethesda-Chevy Chase High School",
  "Beverly Farms Elementary School",
  "Bradley Hills Elementary School",
  "Briggs Chaney Middle School",
  "Brooke Grove Elementary School",
  "Brookhaven Elementary School",
  "Brown Station Elementary School",
  "Burning Tree Elementary School",
  "Burnt Mills Elementary School",
  "Burtonsville Elementary School",
  "Cabin Branch Elementary School",
  "Cabin John Middle School",
  "Candlewood Elementary School",
  "Cannon Road Elementary School",
  "Capt. James E. Daly Elementary School",
  "Carderock Springs Elementary School",
  "Carl Sandburg Learning Center",
  "Cashell Elementary School",
  "Cedar Grove Elementary School",
  "Chevy Chase Elementary School",
  "Clarksburg Elementary School",
  "Clarksburg High School",
  "Clearspring Elementary School",
  "Clopper Mill Elementary School",
  "Cloverly Elementary School",
  "Col. Zadok Magruder High School",
  "Cold Spring Elementary School",
  "College Gardens Elementary School",
  "Cresthaven Elementary School",
  "Damascus Elementary School",
  "Damascus High School",
  "Darnestown Elementary School",
  "Diamond Elementary School",
  "Dr. Charles R. Drew Elementary School",
  "Dr. Martin Luther King, Jr . Middle School",
  "Dr. Sally K. Ride Elementary School",
  "DuFief Elementary School",
  "Earle B. Wood Middle School",
  "East Silver Spring Elementary School",
  "Eastern Middle School",
  "Fairland Elementary School",
  "Fallsmead Elementary School",
  "Farmland Elementary School",
  "Fields Road Elementary School",
  "Flora M. Singer Elementary School",
  "Flower Hill Elementary School",
  "Flower Valley Elementary School",
  "Forest Knolls Elementary School",
  "Forest Oak Middle School",
  "Fox Chapel Elementary School",
  "Francis Scott Key Middle School",
  "Gaithersburg Elementary School",
  "Gaithersburg High School",
  "Gaithersburg Middle School",
  "Galway Elementary School",
  "Garrett Park Elementary School",
  "Georgian Forest Elementary School",
  "Germantown Elementary School",
  "Glen Haven Elementary School",
  "Glenallan Elementary School",
  "Goshen Elementary School",
  "Great Seneca Creek Elementary School",
  "Greencastle Elementary School",
  "Greenwood Elementary School",
  "Hallie Wells Middle School",
  "Harmony Hills Elementary School",
  "Harriet R. Tubman Elementary School",
  "Herbert Hoover Middle School",
  "Highland Elementary School",
  "Highland View Elementary School",
  "Jackson Road Elementary School",
  "James Hubert Blake High School",
  "JoAnn Leleck Elementary School at at Broad Acres",
  "John F. Kennedy High School",
  "John Poole Middle School",
  "John T. Baker Middle School",
  "Jones Lane Elementary School",
  "Judith A. Resnik Elementary School",
  "Julius West Middle School",
  "Kemp Mill Elementary School",
  "Kensington Parkwood Elementary School",
  "Kingsview Middle School",
  "Lake Seneca Elementary School",
  "Lakelands Park Middle School",
  "Lakewood Elementary School",
  "Laytonsville Elementary School",
  "Little Bennett Elementary School",
  "Lois P. Rockwell Elementary School",
  "Longview School",
  "Lucy V. Barnsley Elementary School",
  "Luxmanor Elementary School",
  "MacDonald Knolls Early Childhood Center",
  "Maryvale Elementary School",
  "Meadow Hall Elementary School",
  "Mill Creek Towne Elementary School",
  "Monocacy Elementary School",
  "Montgomery Blair High School",
  "Montgomery Knolls Elementary School",
  "Montgomery Village Middle School",
  "Neelsville Middle School",
  "New Hampshire Estates Elementary School",
  "Newport Mill Middle School",
  "North Bethesda Middle School",
  "North Chevy Chase Elementary School",
  "Northwest High School",
  "Northwood High School",
  "Oak View Elementary School",
  "Oakland Terrace Elementary School",
  "Odessa Shannon Middle School",
  "Olney Elementary School",
  "Paint Branch High School",
  "Parkland Middle School",
  "Pine Crest Elementary School",
  "Piney Branch Elementary School",
  "Poolesville Elementary School",
  "Poolesville High School",
  "Potomac Elementary School",
  "Quince Orchard High School",
  "Rachel Carson Elementary School",
  "Redland Middle School",
  "Richard Montgomery High School",
  "Ridgeview Middle School",
  "Ritchie Park Elementary School",
  "Robert Frost Middle School",
  "Roberto W. Clemente Middle School",
  "Rock Creek Forest Elementary School",
  "Rock Creek Valley Elementary School",
  "Rock Terrace School",
  "Rock View Elementary School",
  "Rockville High School",
  "Rocky Hill Middle School",
  "Rolling Terrace Elementary School",
  "Ronald McNair Elementary School",
  "Rosa M. Parks Middle School",
  "Roscoe R. Nix Elementary School",
  "Rosemary Hills Elementary School",
  "Rosemont Elementary School",
  "S. Christa McAuliffe Elementary School",
  "Sargent Shriver Elementary School",
  "Seneca Valley High School",
  "Sequoyah Elementary School",
  "Seven Locks Elementary School",
  "Shady Grove Middle School",
  "Sherwood Elementary School",
  "Sherwood High School",
  "Silver Creek Middle School",
  "Silver Spring International Middle School",
  "Sligo Creek Elementary School",
  "Sligo Middle School",
  "Snowden Farm Elementary School",
  "Somerset Elementary School",
  "South Lake Elementary School",
  "Spark M. Matsunaga Elementary School",
  "Springbrook High School",
  "Stedwick Elementary School",
  "Stephen Knolls School",
  "Stone Mill Elementary School",
  "Stonegate Elementary School",
  "Strathmore Elementary School",
  "Strawberry Knoll Elementary School",
  "Summit Hall Elementary School",
  "Takoma Park Elementary School",
  "Takoma Park Middle School",
  "Thomas S. Wootton High School",
  "Thomas W. Pyle Middle School",
  "Thurgood Marshall Elementary School",
  "Tilden Middle School",
  "Travilah Elementary School",
  "Upcounty Early Childhood Center (UCECC) at Emory Grove",
  "Viers Mill Elementary School",
  "Walt Whitman High School",
  "Walter Johnson High School",
  "Washington Grove Elementary School",
  "Waters Landing Elementary School",
  "Watkins Mill Elementary School",
  "Watkins Mill High School",
  "Wayside Elementary School",
  "Weller Road Elementary School",
  "Westbrook Elementary School",
  "Westland Middle School",
  "Westover Elementary School",
  "Wheaton High School",
  "Wheaton Woods Elementary School",
  "Whetstone Elementary School",
  "White Oak Middle School",
  "William H. Farquhar Middle School",
  "William Tyler Page Elementary School",
  "Wilson Wims Elementary School",
  "Winston Churchill High School",
  "Wood Acres Elementary School",
  "Woodfield Elementary School",
  "Woodlin Elementary School",
  "Wyngate Elementary School",
] as const;

export function isKnownMcpsSchool(name: string): boolean {
  const t = name.trim();
  if (!t) return false;
  return MCPS_SCHOOL_OPTIONS.some((s) => s.toLowerCase() === t.toLowerCase());
}

export function resolveMcpsSchoolName(name: string): string | null {
  const t = name.trim();
  if (!t) return null;
  return MCPS_SCHOOL_OPTIONS.find((s) => s.toLowerCase() === t.toLowerCase()) ?? null;
}
