import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Security Principles — Guardian",
  description:
    "How Guardian collects, protects, and deletes your data — explained in plain language, including what is not yet implemented.",
};

const sections = [
  {
    id: "data-collected",
    title: "What data we collect",
    paragraphs: [
      "Guardian stores the information you give it: your account email, your profile details, the documents you upload, and the data extracted from those documents (such as names, dates, and policy numbers).",
      "We also keep basic operational records — like when a document was uploaded — so the product can work reliably. We do not collect data from your device beyond what you explicitly provide.",
      "If email reminders are enabled, we send deadline reminder emails to your sign-in address. You can turn these off at any time from the Settings page.",
    ],
  },
  {
    id: "authentication",
    title: "How authentication works",
    paragraphs: [
      "Sign-in is handled through Supabase Auth. When you log in, you receive a session token that identifies you on every request. Pages and APIs that touch your data require a valid session — without one, requests are rejected.",
      "Your password is never stored in plain text; Supabase Auth stores only a secure hash.",
    ],
  },
  {
    id: "access-separation",
    title: "How user access is separated",
    paragraphs: [
      "Every document, profile, alert, and document chat in the database is tied to the account that created it. Row Level Security (RLS) policies are enforced at the database level, which means the database itself refuses to return another user's rows — even if application code contains a bug.",
      "This is user-level access control: you can only read and change data that belongs to you.",
    ],
  },
  {
    id: "file-storage",
    title: "Where your files are stored",
    paragraphs: [
      "Uploaded files are stored in Supabase Storage in a bucket scoped to your account. Files are transferred over HTTPS, so they are encrypted in transit between your device and our servers.",
      "Access to stored files goes through the same authenticated session checks as the rest of the product.",
    ],
  },
  {
    id: "ai-processing",
    title: "How AI processing works",
    paragraphs: [
      "When you choose to analyze a document, Guardian sends it to Anthropic's Claude API to extract key facts and generate plain-language explanations and recommendations. Analysis only happens when you request it. Guardian labels the source of each statement: which facts came directly from your document, which dates were calculated, and which recommendations were generated by AI.",
      "You can also ask follow-up questions about a document you own after it has been analyzed. Chat answers are grounded in that document's analysis, stay private to your account, and use the same Claude AI provider. Chat history is stored with your account and deleted when you delete the document or your account.",
      "AI output can be wrong. Always verify important dates and decisions against the original document, which stays available to you at all times.",
    ],
  },
  {
    id: "not-yet-implemented",
    title: "What is not yet implemented",
    paragraphs: [
      "We believe accurate wording matters more than impressive wording. The following are NOT currently in place, and we will not claim them until they are built and independently verified:",
    ],
    list: [
      "End-to-end or zero-knowledge encryption (our systems can technically access stored files in order to process them)",
      "HIPAA compliance",
      "SOC 2 certification",
      "Guaranteed protection from all breaches — no service can honestly promise this",
    ],
    paragraphsAfter: [
      "What we can accurately say today: data is encrypted in transit, protected by authenticated access, and separated by user-level access controls.",
    ],
  },
  {
    id: "deleting-data",
    title: "How you can delete your data",
    paragraphs: [
      "You can delete any document from within the app. Deleting a document removes its database record, the stored file, and the extracted data, alerts, and chat history tied to it.",
      "You can also delete your entire account from the Settings page. That permanently removes your account, profile, all uploaded documents and stored files, extracted data, alerts, and document chat history.",
    ],
  },
  {
    id: "report-concern",
    title: "How to report a security concern",
    paragraphs: [
      "If you believe you have found a vulnerability or notice anything that looks wrong, email security@guardian.app with a description of the issue. Please do not publicly disclose the issue until we have had a chance to investigate and fix it.",
      "We read every report and will respond as quickly as we can.",
    ],
  },
];

export default function SecurityPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />

      <main className="flex-1">
        <section className="border-b border-stone-200 bg-brand-light/60">
          <div className="mx-auto max-w-3xl px-6 py-16 sm:py-20">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm font-medium text-brand hover:text-brand-dark"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to home
            </Link>
            <h1 className="mt-6 text-3xl font-bold tracking-tight sm:text-4xl">
              Security Principles
            </h1>
            <p className="mt-4 text-lg leading-relaxed text-ink-muted">
              Guardian exists to protect the information you cannot afford to
              lose. This page explains — in plain language — what data we
              hold, how we protect it, and just as importantly, what we do not
              yet do.
            </p>
            <p className="mt-4 rounded-xl border border-brand/20 bg-white p-4 text-sm font-medium text-foreground">
              Security is not an add-on. It is part of the product.
            </p>
          </div>
        </section>

        <section className="mx-auto max-w-3xl px-6 py-14">
          <nav className="mb-12 rounded-2xl border border-stone-200 bg-white p-6">
            <p className="text-sm font-semibold uppercase tracking-widest text-brand">
              On this page
            </p>
            <ul className="mt-3 grid gap-2 text-sm text-ink-muted sm:grid-cols-2">
              {sections.map((s) => (
                <li key={s.id}>
                  <a href={`#${s.id}`} className="hover:text-brand">
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div className="space-y-12">
            {sections.map((s) => (
              <article key={s.id} id={s.id} className="scroll-mt-24">
                <h2 className="text-xl font-semibold tracking-tight">
                  {s.title}
                </h2>
                {s.paragraphs.map((p) => (
                  <p
                    key={p.slice(0, 40)}
                    className="mt-3 leading-relaxed text-ink-muted"
                  >
                    {p}
                  </p>
                ))}
                {s.list && (
                  <ul className="mt-3 list-disc space-y-2 pl-6 text-ink-muted">
                    {s.list.map((item) => (
                      <li key={item.slice(0, 40)} className="leading-relaxed">
                        {item}
                      </li>
                    ))}
                  </ul>
                )}
                {s.paragraphsAfter?.map((p) => (
                  <p
                    key={p.slice(0, 40)}
                    className="mt-3 leading-relaxed text-ink-muted"
                  >
                    {p}
                  </p>
                ))}
              </article>
            ))}
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
