import Link from "next/link";
import {
  ArrowRight,
  Ban,
  Eye,
  KeyRound,
  Lock,
  ShieldCheck,
  Sparkles,
  Trash2,
} from "lucide-react";

const points = [
  {
    icon: Lock,
    title: "Private by default",
    body: "Your account and documents are visible only to you unless you choose to share them.",
  },
  {
    icon: KeyRound,
    title: "Secure sign-in",
    body: "Authentication is handled through Supabase Auth with protected user sessions.",
  },
  {
    icon: ShieldCheck,
    title: "User-level data isolation",
    body: "Every document and profile is tied to its owner, with Row Level Security preventing users from accessing another user's data.",
  },
  {
    icon: Eye,
    title: "You stay in control",
    body: "Upload only what you choose. View, download, or delete your information at any time.",
  },
  {
    icon: Ban,
    title: "No data selling",
    body: "We do not sell your personal information or use it for advertising.",
  },
  {
    icon: Sparkles,
    title: "Transparent AI",
    body: "Guardian shows which facts came directly from your document, which dates were calculated, and which recommendations were generated by AI.",
  },
  {
    icon: Trash2,
    title: "Safe deletion",
    body: "When you delete a document, we remove its database record, associated extracted data, alerts, and stored file.",
  },
];

export default function SecuritySection() {
  return (
    <section id="security" className="bg-white py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-6">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-brand">
            Security &amp; privacy
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Built for the information you cannot afford to lose.
          </h2>
          <p className="mt-4 text-lg text-ink-muted">
            Guardian holds the documents that shape your life — so protecting
            them is not optional. Here is how we do it, in plain language.
          </p>
        </div>

        <div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {points.map(({ icon: Icon, title, body }) => (
            <div
              key={title}
              className="rounded-2xl border border-stone-200 bg-stone-50/60 p-6 transition hover:border-brand/40 hover:shadow-sm"
            >
              <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-brand-light text-brand">
                <Icon className="h-5 w-5" />
              </span>
              <h3 className="mt-4 text-base font-semibold text-foreground">
                {title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-ink-muted">
                {body}
              </p>
            </div>
          ))}

          <div className="flex flex-col justify-between rounded-2xl bg-brand p-6 text-white">
            <div>
              <p className="text-lg font-semibold leading-snug">
                “Security is not an add-on. It is part of the product.”
              </p>
              <p className="mt-3 text-sm leading-relaxed text-teal-100">
                We describe our protections accurately — no buzzwords, no
                overclaiming. Read exactly what we do today and what is still
                on our roadmap.
              </p>
            </div>
            <Link
              href="/security"
              className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-white underline-offset-4 hover:underline"
            >
              Read our Security Principles
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
